name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: dist

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          try {
            git checkout -B gh-pages origin/gh-pages
          } catch {
            git checkout -b gh-pages
          }
          # Remove existing files (excluding .git)
          Get-ChildItem | Where-Object {$_.Name -notlike '.git*'} | Remove-Item -Recurse
          # Copy build output to root
          Copy-Item -Path dist/* -Destination . -Recurse
          # Commit and push changes
          git add .
          git commit -m "Deploy to GitHub Pages" -a
          git push origin gh-pages
        shell: powershell
